version: "3"
services:
    postgres:
      image: postgres:9.5-alpine
      container_name: ${PROJECT_NAME}-postgres
      volumes:
         - "./bin/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "${POSTGRES_PORT}:5432"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /www
      volumes:
          - ./www:/www
          - ./bin/nginx:/etc/nginx/conf.d
      ports:
       - "${PROJECT_PORT}:80"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3
    php-fpm:
      build: bin/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /www
      #      command: composer run migrate &
      volumes:
        - ./www:/www
        - ./bin/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./bin/php-fpm/20-xdebug.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini
      networks:
          testing_net:
              ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
